### ISSUE TITLE
where is the regularization of the Dirichlet distribution parameter \beta as stated in the paper

### ISSUE THREAD

**Issue by d12306** [xiangning-chen/DrNAS#2]
Hello, @xiangning-chen , thanks for your released code. I found in the code, you do not implement the regularization of the Dirichlet distribution parameter \beta as stated in the paper, I am wondering if I understand it wrongly or what? Also, the pathwise gradient estimator is not appearing in the code?

PLease help me with this issue.
Thanks,

**Comment by xiangning-chen** [comment]
Hi @d12306 ,

Thanks for your attention, we will push our latest version these few days.
