### ISSUE TITLE
setting init_channels=16 in train_search.py of DARTS search space gives an error

### ISSUE THREAD

**Issue by optyang** [xiangning-chen/DrNAS#3]
The error appears at:

```python
File ".../DrNAS/DARTS-space/operations.py", line 189, in __init__
    assert C_out % 2 == 0
```
So what value of `init_channels` is expected/allowed? Thanks!

**Comment by xiangning-chen** [comment]
Hi,

Thanks for your attention. 
We simply use the DARTS space, where the init_channels number is set as 36 (for a direct search).

**Comment by optyang** [comment]
> Hi,
> 
> Thanks for your attention.
> We simply use the DARTS space, where the init_channels number is set as 36 (for a direct search).

Thanks for your reply.

Do this mean the DrNAS method only works when `init_channels=36`? Thanks a lot!

**Comment by xiangning-chen** [comment]
Hi,

No, you can change the init_channels for search and evaluation. 
This will result in a different search space.

**Comment by optyang** [comment]
I guess I can't simply change it to another value, as `init_channels=16` does not work. Are you going to fix it? If not, could you imply how it can be fixed? Thanks a lot!

**Comment by xiangning-chen** [comment]
Hi,

This is because that the output channels for the FactorizedReduce module (https://github.com/xiangning-chen/DrNAS/blob/master/DARTS-space/operations.py#L185) must be divisible by 2.
