### ISSUE TITLE
Key Error

### ISSUE THREAD

**Issue by edixiong** [xiangning-chen/DrNAS#4]
After the 25th epoch, I will receive a KeyError:

`Traceback (most recent call last):
  File "train_search.py", line 238, in <module>
    main()
  File "train_search.py", line 151, in main
    optimizer = configure_optimizer(optimizer, torch.optim.SGD(
  File "../net2wider.py", line 84, in configure_optimizer
    state_old = optimizer_old.state_dict()['state'][p.raw_id]
KeyError: 139737672243200`

Any idea how to solve this? Is that a version conflict issue?

**Comment by xiangning-chen** [comment]
Hi,

Thanks for the question.
What's your pytorch version?

**Comment by edixiong** [comment]
Hi,

I used PyTorch 1.8. Should I use an older version?

**Comment by xiangning-chen** [comment]
Hi,

I checked that my version is 1,3.0. Could you please take a try and see whether the bug still exists?

**Comment by edixiong** [comment]
Thanks! There isn't the bug with 1.3.0.

**Comment by edixiong** [comment]
Thanks! There isn't the bug with 1.3.0.
