### ISSUE TITLE
Error in cinfigure_optimizer

### ISSUE THREAD

**Issue by jahdkaran** [xiangning-chen/DrNAS#6]
Hey i'm trying to run /201space/train-search-progressive but there seems to be a problem in the configure_optimizer function and it encounters the following error can you help me figure this out? 

> Traceback (most recent call last):
  File "/content/drive/MyDrive/DrNAS-master/201-space/train_search_progressive.py", line 336, in <module>
    main()
  File "/content/drive/MyDrive/DrNAS-master/201-space/train_search_progressive.py", line 251, in main
    weight_decay=args.weight_decay))
  File "/content/drive/MyDrive/DrNAS-master/net2wider.py", line 84, in configure_optimizer
    state_old = optimizer_old.state_dict()['state'][p.raw_id]
KeyError: 140076590179920

reading [this link](https://github.com/pytorch/pytorch/issues/42428) I believe the problem might be because of the pytorch version i'm using which is 1.10 I don't know what version is required for your code

**Comment by xiangning-chen** [comment]
Hi,

Thanks for your interest, I used the 1.3.0 version.

**Comment by jahdkaran** [comment]
Thanks @xiangning-chen for your feedback and great work,
That solved the problem.
