### ISSUE TITLE
Raw_id in configure_optimizer

### ISSUE THREAD

**Issue by martinferianc** [xiangning-chen/DrNAS#7]
Hi!

Thank you for this code! While trying the code I run into an error while running `configure_optimizer(optimizer_old, optimizer_new):` stating:

```
state_old = optimizer_old.state_dict()['state'][p.raw_id]
KeyError: 140435163178672
```

In general, I do not see a way how the `raw_id` can be mapped to a dictionary key?

Thanks for any pointers/help!

**Comment by martinferianc** [comment]
My take that seems to work, do not use the `raw_id` use it just as a flag to note changes with respect to the widening or manipulation and simply use the index `i` as the key for the dict:

```
for i, p in enumerate(optimizer_new.param_groups[0]['params']):
        if not hasattr(p, 'raw_id'):
            optimizer_new.state[i] = optimizer_old.state_dict()['state'][i]
            continue
        state_old = optimizer_old.state_dict()['state'][i]
        state_new = optimizer_new.state[i]
```

I did not change anything else.

**Comment by xiangning-chen** [comment]
Hi,

Thanks for pointing out this issue, I believe this is because the pytorch version.
What version are you using?

**Comment by martinferianc** [comment]
Hi, thanks for looking into this, I am running with 1.11.0 to make use of the latest functionality. Please see my commend above, would that be enough to fix this? Thanks!

**Comment by linhaojia13** [comment]
> My take that seems to work, do not use the `raw_id` use it just as a flag to note changes with respect to the widening or manipulation and simply use the index `i` as the key for the dict:
> 
> ```
> for i, p in enumerate(optimizer_new.param_groups[0]['params']):
>         if not hasattr(p, 'raw_id'):
>             optimizer_new.state[i] = optimizer_old.state_dict()['state'][i]
>             continue
>         state_old = optimizer_old.state_dict()['state'][i]
>         state_new = optimizer_new.state[i]
> ```
> 
> I did not change anything else.


@martinferianc Hi, did you reproduce the searched results reported in the paper in this way?

**Comment by martinferianc** [comment]
Hi, thank you for looking into this. I was not trying to because that is not my aim, but the code does work.

**Comment by linhaojia13** [comment]
> Hi, thank you for looking into this. I was not trying to because that is not my aim, but the code does work.

Thank you very much!
